language: python
python:
- '2.6'
- '2.7'
- '3.2'
install:
- python setup.py install
script: python test/__init__.py
notifications:
  hipchat:
    rooms:
      secure: EM9R9OJdDnocbOt2oAmm9ZySBN2c/gYItc5VhfrsTGTLip6+nQg+j7/CKvySwoBYbAQQ73Lf/qi0x4x29rWlwXOP0roHoBHKkU19Yf0xD2fXg2v2RYyCndLL6kBMirs3Os/hzMfqlBszmZyJX/Ffrttz0dmOw7H4i3UtNLfLZQ4=
    template:
    - '<a href="https://travis-ci.org/%{repository}/builds/%{build_id}">%{repository}
      Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong>
      <a href="https://github.com/sendgrid/docs/commits/%{commit}">View on GitHub</a>'
    format: html
